### ISSUE TITLE
[BE/ 인증 서버] node 실행파일 실행시 에러

### ISSUE THREAD

**Issue by ummaeha** [STOVE-Milk/steam-clone#41]
![image](https://user-images.githubusercontent.com/48500209/151486158-19965409-3f79-44ab-9f2a-1185665e1f18.png)
좌: nodemon으로 실행
우: 실행파일 더블클릭으로 실행

에러메시지
`pkg/prelude/bootstrap.js:1740
      throw error;
      ^

Error: Cannot find module '/snapshot/backend/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'
Require stack:
- /snapshot/backend/node_modules/bcrypt/bcrypt.js
- /snapshot/backend/routes/auth.js
- /snapshot/backend/app.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1819:46)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
`

**Comment by ummaeha** [comment]
코드 clone 받아서 실행하는 것으로 임시해결

이슈 닫겠습니다
