### ISSUE TITLE
[BE / 로비 서버] 원격 서버에서 소켓 연결 시 Close 오류 다량 발생

### ISSUE THREAD

**Issue by Tae-Hyeon** [STOVE-Milk/steam-clone#83]
### 오류 내용
- message를 보내는 부분에서 발생했다.
  - session이 닫혀있을 경우 메세지를 보내지 않도록 분기 처리 해줌
  - https://github.com/ytw9699/Dokky/issues/257 에 따라 기본적인 오류가 없나 체크해봐야함
``` java
The WebSocket session [4] has been closed and no method (apart from close()) may be called on a closed session
        at org.apache.tomcat.websocket.WsSession.checkState(WsSession.java:1074) ~[tomcat-embed-websocket-9.0.56.jar!/:na]
        at org.apache.tomcat.websocket.WsSession.getBasicRemote(WsSession.java:640) ~[tomcat-embed-websocket-9.0.56.jar!/:na]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:215) ~[spring-websocket-5.3.15.jar!/:5.3.15]
        at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:106) ~[spring-websocket-5.3.15.jar!/:5.3.15]
        at com.steam.library.service.SocketService.sendMessageToMe(SocketService.java:310) ~[classes!/:na]
        at com.steam.library.service.SocketService.sendMessageToMe(SocketService.java:304) ~[classes!/:na]
        at com.steam.library.service.SocketService.sendErrorMessage(SocketService.java:286) ~[classes!/:na]
        at com.steam.library.service.SocketService.enter(SocketService.java:125) ~[classes!/:na]

```
### close 이벤트 받지 못함
- 참고 자료: https://ivvve.github.io/2020/08/17/etc/why-websocket-server-doesnt-emit-close-event/
### move 시 Redis 동기화 오류
- Redis에 유저 이동에 따른 위치 변경 시 오류가 발생한다.
- get해오는 과정에서 NullPointerException 발생
``` java
public synchronized void moveUserInRedis(String roomId, String movedUserId, Direction direction) {
        HashOperations<String, String, Integer> hash = redisTemplate.opsForHash();
        String mainKey = "library:" + roomId;
        String hashKey = "users.[" + movedUserId + "].";
        try {
            if (Boolean.TRUE.equals(hash.hasKey(mainKey, hashKey + 'x'))) { 
                switch (direction) {
                    case UP:
                        hashKey += 'y';
                        if (hash.get(mainKey, hashKey) < MAX_SIDE_OF_MAP)  --> 오류 발생
                            hash.increment(mainKey, hashKey, 1);
                        break;
                    case RIGHT:
                        hashKey += 'x';
                        if (hash.get(mainKey, hashKey) < MAX_SIDE_OF_MAP)
                            hash.increment(mainKey, hashKey, 1);
                        break;
                    case DOWN:
                        hashKey += 'y';
                        if (hash.get(mainKey, hashKey) > 0)
                            hash.increment(mainKey, hashKey, -1);
                        break;
                    case LEFT:
                        hashKey += 'x';
                        if (hash.get(mainKey, hashKey) > 0)
                            hash.increment(mainKey, hashKey, -1);
                        break;
                }
            }
        } catch (NullPointerException e) {
            log.info(mainKey + "." + hashKey);
            log.info(hash.get(mainKey, hashKey).toString());
        }
```

**Comment by Tae-Hyeon** [comment]
문제 1
- 유저가 방에서 나갈 때, 유저 수가 0이라면 방 캐시를 삭제하는 명령이 있는데, 이에 따라 동시성 문제가 발생한 것 같다.
  - 유저 1 입장 - 유저 1 퇴장 + 유저 2 입장 - 유저 1 방 삭제 - 유저 2 이동 - 방 없음 or 캐시 데이터 유저 2만 남아있음 - 유저 3 입장 - 방 데이터 없음

**Comment by Tae-Hyeon** [comment]
문제 2
- 유저가 나갈 때, RedisTemplate을 이용한 명령이 한번에 수행되지 않아서, 순서가 꼬인다. (예상)
  - 유저 삭제 트랜잭션을 RedisTemplate.execute(SessionCallback)을 이용해 한번에 처리한다.
``` java
    public void removeUserInRedis(String roomId, String leaveUserId) {
        String mainKey = "library:" + roomId;
        String hashKey = "users.[" + leaveUserId + "].";
        RLock roomLock = redissonClient.getLock(PREFIX_OF_LOCK + roomId);
        try {
            roomLock.lockInterruptibly(EXPIRE_TIME_OF_LOCK, TIME_UNIT);
            redisTemplate.execute(new SessionCallback<Object>() {
                @Override
                public <K, V> Object execute(RedisOperations<K, V> operations) throws DataAccessException {
                    operations.multi();
                    HashOperations<K, String, Object> hash = operations.opsForHash();
                    hash.increment((K) mainKey, "userCount", -1);
                    hash.delete((K) mainKey, hashKey + 'x');
                    hash.delete((K) mainKey, hashKey + 'y');
                    hash.delete((K) mainKey, hashKey + "nickname");
                    operations.exec();
                    return null;
                }
            });
        } catch (InterruptedException e) {
            e.printStackTrace();
        } finally {
            roomLock.unlock();
        }
    }
```
